development:
  adapter: postgresql
  database: ragnarok_rails_development
  username: socjopata
  password: secret
  pool: 5


test:
  adapter: postgresql
  database: ragnarok_rails_test
  username: socjopata
  password: secret
  pool: 5


production:
  adapter: postgresql
  database: ragnarok_rails_production
  username: socjopata
  password: secret
  pool: 5
